任务详情

以下为上海地区某时期内的二手房数据，存在 houses.csv中，每条房源包含下列信息，请按照要求进行统计分析：
![Jupyter](https://cdn.py2china.cn/study-group/pandas/8-1.png)
用 pandas 读取 csv 格式文件，并将所有字段的重复数据去除（阅读参考文章①②）

1请统计出总房源数量、总小区数量、总版块数量（任务提示：直接统计数据的条数，即用 len 函数即可。阅读参考文章③）

2请统计出有哪些不同的户型、有哪些不同的装修情况、有哪些不同的建造年份（任务提示：可用 unique 函数进行统计。阅读参考文章④）

3请计算出上海二手房每平方米均价

4请统计出不同户型对应的房源数量、平均面积。按不同户型的房源数量，从大到小进行排序，判断出主流户型是什么？平均面积多大？（任务提示：以 huxing 为分组对象，展示 size 列，统计户型数量和 size 平均数。阅读参考文章⑤⑥⑦⑧）

5获取每个小区的房源数量，并按从大到小的顺序排序（阅读参考文章⑤⑥⑦⑧）

6请统计出上海每个小区每平方米的均价（阅读参考文章⑤⑥⑦⑧）

7请统计出上海二手房总价排在前 5 位的房源，看看超级豪宅有多壕？（阅读参考文章⑧）

8请计算出不同年代的房子数量（10年一个区间）（任务提示：先将 buildyear 列转为时间序列，再利用 groupby 函数统计出每年的房源数量，最后用 resample 函数进行汇总。阅读参考文章⑨⑩⑪）

In [105]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [8]:
df=pd.read_csv('houses.csv',encoding='gbk').drop_duplicates()
df.head()

,Unnamed: 0,_id,title,price,up_price,xiaoqu_name,size,buildyear,huxing,chaoxiang,zhuangxiu,cenggao,louxing,district_name,sub_district_name
0,0,5dd2198f18bba2b4a9a0b854,大华电梯两房/房型正气/开门南北通/房东诚意出售,690.0,76531,大华锦绣华城(十六街区)(公寓),90.16,2010,2室2厅,南,简装,中楼层(共18层),板楼,浦东,北蔡
1,1,5dd2198f18bba2b4a9a0b855,非底楼 满五年唯一 税费少 婚房装修 楼称佳 户型方正,330.0,52290,芳雅苑,63.11,1995,2室1厅,南,精装,低楼层(共6层),板楼,浦东,北蔡
2,2,5dd2198f18bba2b4a9a0b856,满五唯一+7号线锦绣路+复式房+带阁楼+小区央位+精装,500.0,62878,锦博苑,79.52,2007,2室2厅,南,精装,高楼层(共6层),板楼,浦东,北蔡
3,3,5dd2198f18bba2b4a9a0b857,13号线陈春路地铁400米中间楼层诚意卖看房方便,330.0,45866,鹏海小区,71.95,1997,2室1厅,南,简装,中楼层(共6层),板楼,浦东,北蔡
4,4,5dd2198f18bba2b4a9a0b858,朝阳正气一房，采光好，坐看花园，户型方正，看房方便,460.0,83942,万邦都市花园,54.80,2004,1室1厅,南,简装,中楼层(共11层),板楼,浦东,北蔡

1请统计出总房源数量、总小区数量、总版块数量（任务提示：直接统计数据的条数，即用 len 函数即可。阅读参考文章③）

In [16]:
print('总房源数：',len(df.index))
print('总小区数：',len(df.xiaoqu_name.drop_duplicates()))
print('总版块数：',len(df.sub_district_name.drop_duplicates()))

总房源数： 69654
总小区数： 8333
总版块数： 165

2请统计出有哪些不同的户型、有哪些不同的装修情况、有哪些不同的建造年份（任务提示：可用 unique 函数进行统计。阅读参考文章④）

In [22]:
print('户型：',df.huxing.unique())
print('装修：',df.zhuangxiu.unique())
print('建造年份：',df.buildyear.unique())

户型： ['2室2厅 ' '2室1厅 ' '1室1厅 ' '4室3厅 ' '3室1厅 ' '3室2厅 ' '4室2厅 ' '1室2厅 ' '2室0厅 '
 '5室1厅 ' '1室0厅 ' '5室3厅 ' '5室2厅 ' '4室1厅 ' '4室4厅 ' '6室3厅 ' '5室6厅 ' '6室2厅 '
 '5室4厅 ' '7室3厅 ' '3室3厅 ' '9室2厅 ' '7室2厅 ' '7室1厅 ' '6室4厅 ' '6室1厅 ' '8室4厅 '
 '3室0厅 ' '7室4厅 ' '7室5厅 ' '4室5厅 ' '9室6厅 ' '9室4厅 ' '6室5厅 ' '10室1厅 ' '4室0厅 '
 '8室1厅 ' '9室3厅 ' '9室9厅 ' '5室5厅 ' '8室3厅 ' '2室3厅 ' '7室6厅 ' '8室2厅 ' '0室0厅 '
 '6室6厅 ' '10室6厅 ' '2室4厅 ' '6室0厅 ' '10室2厅 ' '7室0厅 ' '3室4厅 ' '8室5厅 '
 '10室3厅 ' '5室0厅 ' '3室5厅 ']
装修： [' 简装 ' ' 精装 ' ' 毛坯 ' ' 其他 ']
建造年份： [2010 1995 2007 1997 2004 1994 2011 2012 1998 2013 1999 2016 2000 2005
 1996 2003 2015 2006 2009 1993 2002 2014 1992 2008 2001 2019 2018 1987
 1991 2017 1989 1988 1982 1983 1984 1981 1985 1977 1986 1990 1979 1980
 1953 1976 1958 1978 1969 1974 1975 1955 1971 1954 1956 1959 1968 1964
 1960 1967 1972 1961 1973 1936 1911 1941 1948 1949 1939 1933 1940 1946
 1937 1910 1945 1957 1965 1966 1970 1963 1950 1962 1930 1920 1947 1938
 1934 1935 1921 1926 1912 1924 1928 1931 1943 1900 1952 1951]

3请计算出上海二手房每平方米均价

In [23]:
df.up_price.mean()

55051.4809056192

4请统计出不同户型对应的房源数量、平均面积。按不同户型的房源数量，从大到小进行排序，判断出主流户型是什么？平均面积多大？（任务提示：以 huxing 为分组对象，展示 size 列，统计户型数量和 size 平均数。阅读参考文章⑤⑥⑦⑧）

In [69]:
df.pivot_table(index='huxing',values='size',aggfunc=[len,np.mean]).sort_values(by=('len','size'),ascending=False)

            len         mean
           size         size
huxing
2室1厅    17364.0    66.915066
2室2厅    12990.0    93.016552
3室2厅    12618.0   129.362787
1室1厅    12103.0    46.955651
4室2厅     3613.0   208.867312
3室1厅     3451.0    91.561336
1室0厅     1914.0    36.206541
2室0厅     1369.0    49.615223
1室2厅     1192.0    67.410990
5室2厅      855.0   286.614175
5室3厅      584.0   360.780565
4室3厅      566.0   272.177951
6室3厅      181.0   395.391215
6室2厅      147.0   289.408435
4室1厅      145.0   154.547586
3室3厅      134.0   175.504030
3室0厅      107.0    68.571869
5室4厅       51.0   403.056667
6室4厅       49.0   516.186122
7室3厅       36.0   461.077222
5室1厅       32.0   225.869375
7室2厅       30.0   310.042667
4室4厅       21.0   265.587143
6室1厅       11.0   170.230909
7室4厅        9.0   535.334444
8室2厅        9.0   366.875556
2室3厅        8.0   118.597500
6室5厅        7.0   669.482857
8室3厅        6.0   474.710000
7室5厅        5.0   532.396000
8室4厅        5.0   622.384000
9室2厅        4.0   757.650000
0室0厅        4.0   237.622500
9室4厅        3.0   409.463333
4室0厅        3.0   192.590000
5室6厅        3.0   344.720000
6室0厅        2.0   504.425000
5室5厅        2.0   334.585000
9室6厅        2.0   473.775000
7室1厅        2.0   177.200000
7室6厅        2.0   406.005000
2室4厅        1.0   129.400000
9室3厅        1.0   593.010000
10室2厅       1.0   370.000000
8室5厅        1.0  1663.100000
10室3厅       1.0   598.320000
10室6厅       1.0   473.610000
3室4厅        1.0    94.370000
8室1厅        1.0   386.170000
3室5厅        1.0   376.210000
4室5厅        1.0   321.000000
7室0厅        1.0   161.440000
6室6厅        1.0  1440.160000
5室0厅        1.0    89.600000
10室1厅       1.0   544.990000
9室9厅        1.0  1352.240000

5获取每个小区的房源数量，并按从大到小的顺序排序

In [83]:
df.xiaoqu_name.value_counts()

上海康城         216
同润菲诗艾伦       117
中远两湾城        114
美岸栖庭(公寓)     106
金地艺境(宝山)     106
            ...
虬江路843号        1
陆丰路146号        1
兰溪路243号        1
延吉东路131弄       1
云锦雅苑           1
Name: xiaoqu_name, Length: 8333, dtype: int64

6请统计出上海每个小区每平方米的均价（阅读参考文章⑤⑥⑦⑧）

In [84]:
df.pivot_table(index='xiaoqu_name',values='up_price')

                   up_price
xiaoqu_name
MAX未来          31574.105263
VIP大厦          70574.000000
一品名人居          76460.166667
一品新筑苑          65559.700000
一品漫城(一期)(公寓)   55750.400000
...                     ...
龙阳小区           65840.666667
龙阳花苑           72077.800000
龚华公寓           33396.250000
龚华新村           34649.312500
龚路新城           33937.764706

[8333 rows x 1 columns]

7请统计出上海二手房总价排在前 5 位的房源，看看超级豪宅有多壕？

In [96]:
df.sort_values(by='price',ascending=False).head()

,Unnamed: 0,_id,title,price,up_price,xiaoqu_name,size,buildyear,huxing,chaoxiang,zhuangxiu,cenggao,louxing,district_name,sub_district_name
46396,48887,5dd22309303c5558c090e6d9,花园18亩 开门见3座山 背面靠山 南东2面临天然大河,35000.0,191890,世茂佘山庄园,1823.97,2008,6室3厅,南,毛坯,2层,板楼,松江,佘山
46451,48943,5dd22309303c5558c090e711,仟万精装、华庭岛屿大独栋！5亩占地、自住！价格可谈,30000.0,189672,佘山高尔夫郡,1581.68,2009,6室3厅,南 北,精装,2层,板楼,松江,佘山
18891,19869,5dd21bf518bba2b4a9a1061f,罕见！占地10亩庄园，整个园区的King！让上海都在仰望,30000.0,156613,绿城玫瑰园,1915.56,2013,6室4厅,南,毛坯,2层,板楼,闵行,马桥
28332,29721,5dd21d0718bba2b4a9a12cb3,安福路/常熟路 沿街独幢花园洋房，英式风格 地价已补,24999.0,527406,常熟路182号,474.00,1937,6室3厅,南,精装,低楼层(共3层),板塔结合,徐汇,衡山路
18875,19853,5dd21bf418bba2b4a9a1060f,（岛宅主推）占地8亩上产证 两面邻水靠大河 景观位置,21000.0,128214,绿城玫瑰园,1637.89,2014,6室4厅,南,毛坯,2层,板楼,闵行,马桥

8请计算出不同年代的房子数量（10年一个区间）（任务提示：先将 buildyear 列转为时间序列，再利用 groupby 函数统计出每年的房源数量，最后用 resample 函数进行汇总。阅读参考文章⑨⑩⑪）

In [144]:
date=pd.to_datetime(df.buildyear,format='%Y')
df.buildyear=date
df.groupby('buildyear').count().resample('10AS').sum()['_id']

buildyear
1900-01-01        1
1910-01-01        6
1920-01-01       24
1930-01-01      116
1940-01-01       49
1950-01-01      398
1960-01-01      258
1970-01-01      872
1980-01-01     7887
1990-01-01    23257
2000-01-01    24463
2010-01-01    12323
Freq: 10AS-JAN, Name: _id, dtype: int64